const paragraphs = [
    "Sans rigoler. Je pratique la MMA depuis maintenant 6 ans, de la boxe en parallèle depuis 7 ans, je pourrai. Ainsi que la musculation depuis 4 ans, 1m87 pour 86 kg. J'ai une vitesse de fou, et des réflexes identiques à ma vitesse. J'ai juste à l'attendre qu'il me charge, l'esquiver et lui donner des bonnes patates dans la tête. Je le lâcherai pas à la moindre erreur, le gorille est fini. T'auras toujours des puceaux d'ici pour penser que c'est impossible. Rien n'est impossible avec de la volonté déjà les amis, et de 2) c'est pas avec votre corps de lâche que vous allez faire quoi que ce soit. N'importe quel homme un minimum entraîné peut vaincre un gorille avec un couteau déjà. À main nue c'est pas forcément plus compliqué ça demande juste de la technique.",
    "Bidoof is a brown, rodent-like Pokémon with four short legs. It has a short, dark brown snout and a small, red nose. Cream-colored markings cover its underside and surround its face. Round tufts of fur form its tail with five on the male and three on the female. Similar tufts line the bottom of its face and two singular ones form its ears. Bidoof's black paws have three toes with some webbing between them. Protruding from Bidoof's upper jaw are large incisors, which it uses for gnawing on wood and rocks. These teeth grow constantly, so this Pokémon needs to gnaw on hard substances to keep them ground down. This Pokémon can be found nesting in groups near bodies of water. Despite its stout body, this Pokémon can be agile and is not easily perturbed.",
    "An enthusiastic yordle sorcerer, Veigar has embraced powers that few others dare even approach. As a free-spirited inhabitant of Bandle City, he once longed to learn more of the celestial magic practiced by mortals, but his natural curiosity was twisted by imprisonment in the Immortal Bastion. Now a stubborn creature with the dark fury of the stars at his command, Veigar is often underestimated by others—and though he believes himself truly evil, there are some who still question his deeper motivations.",
    "It looked as if it was running on its side, the way dogs run when they think they are chasing a cat in a dream.",
    "But the dog was not running or asleep.",
    "The dog was dead.",
    "There was a garden fork sticking out of the dog.",
    "The points of the fork must have gone all the way through the dog and into the ground because the fork had not fallen over.",
    "I decided that the dog was probably killed with the fork because I could not see any other wounds in the dog and I do not think you would stick a garden fork into a dog after it had died for some other reason, like cancer for example, or a road accident.",
    "But I could not be certain about this."
]